### ISSUE TITLE
Dumpster places into nodes

### ISSUE THREAD

**Issue by NathanSalapat** [4Evergreen4/trash_can#3]
If you have a space 1 node wide and put a dumpster into that space it will place into the next node creating an odd look.

You might want to consider adding some code to check if the space is clear before placing the dumpster.

**Comment by 4Evergreen4** [comment]
This is a known issue, I just have been too busy on other projects to update this.  If anyone wants to craete a pull request for a fix, I would be fine with it.

**Comment by NathanSalapat** [comment]
I can probably that, it was annoying me so fixing it would make sense. :-)
